on:
  push:
    branches:
      - master
    paths:
      - "projects/**.yaml"

env:
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RCTL_API_KEY: ${{ secrets.RCTL_API_KEY }}
  RCTL_API_SECRET: ${{ secrets.RCTL_API_SECRET }}
  RCTL_REST_ENDPOINT: ${{ secrets.RCTL_REST_ENDPOINT }}

jobs:
  infrastructure-provisioner:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: configure git
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
        
      - name: set environment variables
        run: |
          cluster_spec=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -v 'deployment.yaml')
          cluster_name=${cluster_spec#projects/*/}
          cluster_name=${cluster_name%/cluster-spec.yaml}
          deployment=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -v 'cluster-spec.yaml')
          project=${deployment#projects/}
          project=${project%/*/deployment.yaml}
          
          echo "CLUSTER_NAME=${cluster_name}" >> $GITHUB_ENV
          echo "DEPLOYMENT=${deployment}" >> $GITHUB_ENV
          echo "PROJECT=${project}" >> $GITHUB_ENV
          echo "RCTL_PROJECT=${project}" >> $GITHUB_ENV
          
          if [ -e "${cluster_spec}" ]; then
            echo "ACTION=provision" >> $GITHUB_ENV
          else
            echo "ACTION=destroy" >> $GITHUB_ENV
          fi
        
      - name: gcloud auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ env.GCP_SERVICE_ACCOUNT }}'
        
      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0
        
      - name: rctl setup
        run: |
          curl -s https://rafay-prod-cli.s3-us-west-2.amazonaws.com/publish/rctl-linux-amd64.tar.bz2 -o ${HOME}/rctl-linux-amd64.tar.bz2
          tar -C ${HOME} -xf ${HOME}/rctl-linux-amd64.tar.bz2
          chmod 0755 ${HOME}/rctl
          mkdir -p ${HOME}/.rafay/cli
        
      - name: provision gke cluster
        if: env.ACTION == 'provision'
        run: |
          if [ -n "$(gcloud deployment-manager deployments list | grep ${CLUSTER_NAME})" ]; then
            echo "error: cluster already exists, exiting"
            exit 1
          else
            cd projects/${PROJECT}/${CLUSTER_NAME}
            ${HOME}/rctl create cluster -f cluster-spec.yaml
          fi
        
      - name: destroy gke cluster
        if: env.ACTION == 'destroy'
        run: |
          if [ -z "$(gcloud deployment-manager deployments list | grep ${CLUSTER_NAME})" ]; then
            echo "error: cluster does not exist, exiting"
            exit 1
          else
            if [ -n "$(${HOME}/rctl get clusters | grep ${CLUSTER_NAME})" ]; then
              ${HOME}/rctl delete cluster ${CLUSTER_NAME} -y
            fi
            gcloud deployment-manager deployments delete ${CLUSTER_NAME} --async --quiet
          fi